version: '3'

services:
  file-storage-index:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-storage-index
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add other environment variables if needed
    volumes:
      - file-storage-data:/app/data

volumes:
  file-storage-data:
    # This creates a named volume that persists even when containers are removed 