version: '3'

services:
  file-storage-index:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-storage-index
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - file-storage-data:/app/data
    ports:
      - "3000:3000"

volumes:
  file-storage-data: